// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpVgYbXzzYSh-y1PdgX195TthpssSfsj8',
    appId: '1:1029567982628:web:078e7a8c24bdb192c8fcb1',
    messagingSenderId: '1029567982628',
    projectId: 'mynotes-flutter-001',
    authDomain: 'mynotes-flutter-001.firebaseapp.com',
    storageBucket: 'mynotes-flutter-001.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnIevvmqJHxHjCX6k6Gd1Acd2_xQWJtM0',
    appId: '1:1029567982628:android:ddf70056818aa232c8fcb1',
    messagingSenderId: '1029567982628',
    projectId: 'mynotes-flutter-001',
    storageBucket: 'mynotes-flutter-001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtl8ryNLOGONpzTZHTqp1fG_zYu79xr9Q',
    appId: '1:1029567982628:ios:9dfbf6068113c276c8fcb1',
    messagingSenderId: '1029567982628',
    projectId: 'mynotes-flutter-001',
    storageBucket: 'mynotes-flutter-001.appspot.com',
    iosClientId: '1029567982628-6b20spt74j99u1mpe7jqfpgttfhbk33d.apps.googleusercontent.com',
    iosBundleId: 'dev.embed-labs.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtl8ryNLOGONpzTZHTqp1fG_zYu79xr9Q',
    appId: '1:1029567982628:ios:9114974c2f4d7d70c8fcb1',
    messagingSenderId: '1029567982628',
    projectId: 'mynotes-flutter-001',
    storageBucket: 'mynotes-flutter-001.appspot.com',
    iosClientId: '1029567982628-mob3dbktg54hgfp40raata5d2ejhk2sg.apps.googleusercontent.com',
    iosBundleId: 'dev.embed-labs.mynotes.RunnerTests',
  );
}
